# Generated by Django 6.0.4 on 2026-04-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('indeed', 'Indeed')], default='linkedin', max_length=20),
        ),
    ]
